/*
|--------------------------------------------------------------------------
| WHAT IS A CUSTOM DOMAIN?
|--------------------------------------------------------------------------
|
| By default, CloudFront gives you:
|
| https://xxxxx.cloudfront.net
|
|
| Example:
|
| https://dl8mds9i7bu5u.cloudfront.net
|
|
| But users usually prefer:
|
| https://yourdomain.com
|
| OR:
|
| https://app.yourdomain.com
|
|
| Example:
|
| https://aws-test.havenastays.net
|
|
| A custom domain is simply:
|
| A human-friendly alias for CloudFront.
|
*/


/*
|--------------------------------------------------------------------------
| IMPORTANT UNDERSTANDING
|--------------------------------------------------------------------------
|
| Your domain DOES NOT host your app.
|
|
| Your app is still hosted on:
|
| ✅ S3
| ✅ CloudFront
|
|
| Your domain ONLY points users to CloudFront.
|
|
| Think of domains like:
|
| A readable address.
|
*/


/*
|--------------------------------------------------------------------------
| FINAL DOMAIN FLOW
|--------------------------------------------------------------------------
|
| User
|   ↓
| aws-test.havenastays.net
|   ↓
| Namecheap DNS
|   ↓
| CloudFront
|   ↓
| S3 Bucket
|   ↓
| React App
|
*/


/*
|--------------------------------------------------------------------------
| WHAT IS DNS?
|--------------------------------------------------------------------------
|
| DNS means:
|
| Domain Name System
|
|
| DNS translates:
|
| aws-test.havenastays.net
|
| INTO:
|
| The actual server handling requests.
|
|
| Without DNS:
|
| Browsers would need to remember IP addresses.
|
*/


/*
|--------------------------------------------------------------------------
| WHAT IS A SUBDOMAIN?
|--------------------------------------------------------------------------
|
| Main domain:
|
| havenastays.net
|
|
| Subdomain:
|
| aws-test.havenastays.net
|
|
| Structure:
|
| aws-test  → subdomain
| havenastays → root domain
| .net → TLD
|
|
| Companies commonly use:
|
| app.domain.com
| api.domain.com
| admin.domain.com
|
*/


/*
|--------------------------------------------------------------------------
| WHY USE SUBDOMAINS?
|--------------------------------------------------------------------------
|
| Cleaner architecture.
|
|
| Example:
|
| Main Website:
| havenastays.net
|
|
| Frontend App:
| app.havenastays.net
|
|
| Backend API:
| api.havenastays.net
|
|
| Admin Dashboard:
| admin.havenastays.net
|
*/


/*
|--------------------------------------------------------------------------
| WHAT IS A CNAME RECORD?
|--------------------------------------------------------------------------
|
| CNAME means:
|
| Canonical Name
|
|
| A CNAME creates:
|
| An alias from one domain to another.
|
|
| Example:
|
| aws-test.havenastays.net
|               ↓
| dl8mds9i7bu5u.cloudfront.net
|
|
| Meaning:
|
| "aws-test is an alias for this CloudFront distribution"
|
*/


/*
|--------------------------------------------------------------------------
| IMPORTANT UNDERSTANDING
|--------------------------------------------------------------------------
|
| CloudFront ALREADY has a real domain:
|
| xxxxx.cloudfront.net
|
|
| Your custom domain simply points to it.
|
*/


/*
|--------------------------------------------------------------------------
| STEP 1 — CREATE CLOUDFRONT DISTRIBUTION
|--------------------------------------------------------------------------
|
| Example generated by AWS:
|
| dl8mds9i7bu5u.cloudfront.net
|
|
| At this point:
|
| ✅ CloudFront works
| ✅ HTTPS works
|
| BUT:
|
| Only using AWS URL.
|
*/


/*
|--------------------------------------------------------------------------
| STEP 2 — REQUEST SSL CERTIFICATE
|--------------------------------------------------------------------------
|
| CloudFront CANNOT use your custom domain
| without SSL.
|
|
| AWS uses:
|
| AWS Certificate Manager (ACM)
|
*/


/*
|--------------------------------------------------------------------------
| VERY IMPORTANT REGION RULE
|--------------------------------------------------------------------------
|
| CloudFront certificates MUST be created in:
|
| us-east-1
|
|
| NOT:
|
| eu-north-1
| us-west-2
| etc.
|
|
| WHY?
|
| CloudFront globally uses certificates
| from N. Virginia only.
|
*/


/*
|--------------------------------------------------------------------------
| STEP 3 — REQUEST CERTIFICATE
|--------------------------------------------------------------------------
|
| Example:
|
| aws-test.havenastays.net
|
|
| Choose:
|
| DNS Validation
|
|
| WHY?
|
| Easier and automatic.
|
*/


/*
|--------------------------------------------------------------------------
| WHAT IS DNS VALIDATION?
|--------------------------------------------------------------------------
|
| AWS needs proof that:
|
| You own the domain.
|
|
| So AWS generates:
|
| A special DNS CNAME record.
|
|
| Example:
|
| Host:
| _abc.aws-test
|
|
| Value:
| _xyz.acm-validations.aws
|
*/


/*
|--------------------------------------------------------------------------
| VERY IMPORTANT UNDERSTANDING
|--------------------------------------------------------------------------
|
| This validation CNAME:
|
| DOES NOT serve your website.
|
|
| It ONLY proves:
|
| "You own this domain"
|
*/


/*
|--------------------------------------------------------------------------
| STEP 4 — GO TO NAMECHEAP
|--------------------------------------------------------------------------
|
| Namecheap
|   ↓
| Domain List
|   ↓
| Manage
|   ↓
| Advanced DNS
|
*/


/*
|--------------------------------------------------------------------------
| WHAT IS NAMECHEAP DOING?
|--------------------------------------------------------------------------
|
| Namecheap is NOT hosting your app.
|
|
| Namecheap ONLY:
|
| ✅ manages your domain
| ✅ manages DNS records
|
|
| Think of Namecheap like:
|
| A phonebook for the internet.
|
*/


/*
|--------------------------------------------------------------------------
| STEP 5 — ADD ACM VALIDATION RECORD
|--------------------------------------------------------------------------
|
| Add:
|
| CNAME Record
|
|
| Example:
|
| Host:
| _abc.aws-test
|
|
| Value:
| _xyz.acm-validations.aws
|
*/


/*
|--------------------------------------------------------------------------
| IMPORTANT NAMECHEAP RULE
|--------------------------------------------------------------------------
|
| If AWS gives:
|
| _abc.aws-test.havenastays.net
|
|
| In Namecheap Host field use ONLY:
|
| _abc.aws-test
|
|
| NOT:
|
| the full domain.
|
|
| WHY?
|
| Namecheap automatically appends:
|
| .havenastays.net
|
*/


/*
|--------------------------------------------------------------------------
| STEP 6 — CERTIFICATE BECOMES ISSUED
|--------------------------------------------------------------------------
|
| AWS checks DNS periodically.
|
|
| Eventually:
|
| Pending Validation
|         ↓
| Issued
|
|
| This means:
|
| ✅ domain ownership verified
| ✅ HTTPS certificate ready
|
*/


/*
|--------------------------------------------------------------------------
| STEP 7 — ATTACH DOMAIN TO CLOUDFRONT
|--------------------------------------------------------------------------
|
| CloudFront
|   ↓
| Distribution
|   ↓
| Add Domain
|
|
| Example:
|
| aws-test.havenastays.net
|
|
| Then:
|
| Select ACM certificate.
|
*/


/*
|--------------------------------------------------------------------------
| WHAT THIS DOES
|--------------------------------------------------------------------------
|
| CloudFront now understands:
|
| Requests for:
|
| aws-test.havenastays.net
|
| belong to THIS distribution.
|
*/


/*
|--------------------------------------------------------------------------
| STEP 8 — CREATE ACTUAL TRAFFIC CNAME
|--------------------------------------------------------------------------
|
| THIS is the IMPORTANT routing record.
|
|
| Add:
|
| Type:
| CNAME
|
|
| Host:
| aws-test
|
|
| Value:
| dl8mds9i7bu5u.cloudfront.net
|
*/


/*
|--------------------------------------------------------------------------
| WHAT THIS CNAME DOES
|--------------------------------------------------------------------------
|
| It tells DNS:
|
| aws-test.havenastays.net
|               ↓
| send traffic to CloudFront
|
*/


/*
|--------------------------------------------------------------------------
| IMPORTANT UNDERSTANDING
|--------------------------------------------------------------------------
|
| You created TWO DIFFERENT CNAME records.
|
|
| These are DIFFERENT things.
|
*/


/*
|--------------------------------------------------------------------------
| CNAME #1 — ACM VALIDATION RECORD
|--------------------------------------------------------------------------
|
| Example:
|
| _abc.aws-test
|
|
| PURPOSE:
|
| Proves domain ownership to AWS.
|
|
| DOES NOT:
|
| serve your app.
|
*/


/*
|--------------------------------------------------------------------------
| CNAME #2 — CLOUDFRONT ROUTING RECORD
|--------------------------------------------------------------------------
|
| Example:
|
| aws-test
|
|
| PURPOSE:
|
| Routes users to CloudFront.
|
|
| THIS is the real traffic record.
|
*/


/*
|--------------------------------------------------------------------------
| WHY NXDOMAIN HAPPENED
|--------------------------------------------------------------------------
|
| Initially:
|
| You only had:
|
| ACM validation record.
|
|
| BUT:
|
| You did NOT have:
|
| actual CloudFront routing CNAME.
|
|
| Therefore:
|
| DNS could not find:
|
| aws-test.havenastays.net
|
|
| Result:
|
| DNS_PROBE_FINISHED_NXDOMAIN
|
|
| Meaning:
|
| "This domain does not exist yet"
|
*/


/*
|--------------------------------------------------------------------------
| STEP 9 — WAIT FOR PROPAGATION
|--------------------------------------------------------------------------
|
| DNS changes spread globally across:
|
| ✅ ISPs
| ✅ DNS servers
| ✅ browsers
| ✅ network caches
|
|
| Typical propagation:
|
| 5 mins — 48 hours
|
|
| Usually much faster.
|
*/


/*
|--------------------------------------------------------------------------
| STEP 10 — DEFAULT ROOT OBJECT
|--------------------------------------------------------------------------
|
| VERY IMPORTANT.
|
| In CloudFront:
|
| Set:
|
| index.html
|
|
| WHY?
|
| Without this:
|
| Visiting:
|
| https://aws-test.havenastays.net
|
| may fail.
|
*/


/*
|--------------------------------------------------------------------------
| STEP 11 — FINAL TEST
|--------------------------------------------------------------------------
|
| Open:
|
| https://aws-test.havenastays.net
|
|
| You should see:
|
| ✅ React app
| ✅ HTTPS lock
| ✅ CloudFront delivery
| ✅ Custom subdomain working
|
*/


/*
|--------------------------------------------------------------------------
| WHAT ACM ACTUALLY DOES
|--------------------------------------------------------------------------
|
| ACM manages:
|
| ✅ SSL certificates
| ✅ HTTPS encryption
| ✅ certificate renewal
|
|
| Without ACM:
|
| HTTPS would fail.
|
*/


/*
|--------------------------------------------------------------------------
| WHAT CLOUDFRONT ACTUALLY DOES
|--------------------------------------------------------------------------
|
| CloudFront:
|
| ✅ serves files globally
| ✅ caches assets
| ✅ handles HTTPS
| ✅ improves performance
| ✅ reduces latency
|
*/


/*
|--------------------------------------------------------------------------
| WHAT NAMECHEAP ACTUALLY DOES
|--------------------------------------------------------------------------
|
| Namecheap:
|
| ❌ does NOT host your app
|
|
| Namecheap ONLY:
|
| ✅ owns the domain
| ✅ manages DNS
|
*/


/*
|--------------------------------------------------------------------------
| REAL PRODUCTION FLOW
|--------------------------------------------------------------------------
|
| Browser
|   ↓
| DNS Lookup
|   ↓
| Namecheap DNS
|   ↓
| CloudFront
|   ↓
| S3 Bucket
|   ↓
| React Files
|
*/


/*
|--------------------------------------------------------------------------
| MOST IMPORTANT THINGS YOU LEARNED
|--------------------------------------------------------------------------
|
| ✅ Domain ≠ Hosting
|
| ✅ CNAME = Alias
|
| ✅ ACM validation record ≠ traffic record
|
| ✅ CloudFront requires SSL for custom domains
|
| ✅ Namecheap only manages DNS
|
| ✅ CloudFront handles actual traffic
|
| ✅ DNS propagation is not instant
|
*/